#!/usr/bin/env python3
"""Generate ACM-friendly LaTeX figure fragments from campaign CSV output."""

from __future__ import annotations

import csv
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CSV_PATH = ROOT / "reports" / "simulation-campaign-v10.csv"
FIGURE_DIR = ROOT / "paper" / "figures"


def read_averages() -> dict[str, dict[str, float]]:
    totals: dict[str, defaultdict[str, float]] = {}
    counts: dict[str, int] = {}
    with CSV_PATH.open(newline="") as handle:
        for row in csv.DictReader(handle):
            key = row["scenarioKey"]
            totals.setdefault(key, defaultdict(float))
            counts[key] = counts.get(key, 0) + 1
            for field in (
                "productivity",
                "enactedPerRun",
                "welfare",
                "lowSupport",
                "policyShift",
                "proposerGain",
                "challengeRate",
                "compromise",
            ):
                totals[key][field] += float(row[field])
    return {
        key: {field: value / counts[key] for field, value in values.items()}
        for key, values in totals.items()
    }


def fmt(value: float) -> str:
    return f"{value:.1f}"


def write_productivity_low_support(averages: dict[str, dict[str, float]]) -> None:
    points = [
        ("supermajority-60", "S60", 1.5, -4.0),
        ("simple-majority", "SM", 1.5, 2.5),
        ("default-pass", "DP", 2.0, 2.2),
        ("default-pass-mediation", "DP+Med", -16.0, 4.0),
        ("default-pass-challenge", "Chal.", 2.0, -4.0),
        ("default-pass-cross-bloc", "Cross", 2.0, 3.0),
        ("default-pass-adaptive-track", "Adapt", 2.0, -4.0),
        ("default-pass-sunset-trial", "Sunset", 2.0, 2.4),
        ("default-pass-earned-credits", "Credit", -16.0, 2.4),
        ("default-pass-informed-guarded", "Guard", 2.0, -4.0),
        ("default-pass-anti-capture-bundle", "AntiCap", -18.0, -4.0),
    ]
    left, bottom, width, height = 23.0, 14.0, 90.0, 58.0
    lines = [
        "% Auto-generated by paper/scripts/generate_figures.py",
        "\\begingroup",
        "\\setlength{\\unitlength}{1mm}",
        "\\begin{picture}(128,84)",
        "\\scriptsize",
    ]
    for tick in (0.0, 0.25, 0.5, 0.75, 1.0):
        x = left + tick * width
        y = bottom + tick * height
        lines.extend([
            f"\\put({fmt(x)},{fmt(bottom)}){{\\color{{black!15}}\\line(0,1){{{fmt(height)}}}}}",
            f"\\put({fmt(left)},{fmt(y)}){{\\color{{black!15}}\\line(1,0){{{fmt(width)}}}}}",
            f"\\put({fmt(x)},{fmt(bottom - 3.0)}){{\\makebox(0,0){{{tick:.2g}}}}}",
            f"\\put({fmt(left - 4.0)},{fmt(y)}){{\\makebox(0,0)[r]{{{tick:.2g}}}}}",
        ])
    lines.extend([
        f"\\put({fmt(left)},{fmt(bottom)}){{\\line(1,0){{{fmt(width)}}}}}",
        f"\\put({fmt(left)},{fmt(bottom)}){{\\line(0,1){{{fmt(height)}}}}}",
    ])
    for key, label, dx, dy in points:
        x = left + averages[key]["productivity"] * width
        y = bottom + averages[key]["lowSupport"] * height
        lines.extend([
            f"\\put({fmt(x)},{fmt(y)}){{\\makebox(0,0){{\\color{{black}}\\rule{{1.5mm}}{{1.5mm}}}}}}",
            f"\\put({fmt(x + dx)},{fmt(y + dy)}){{\\makebox(0,0)[l]{{{label}}}}}",
        ])
    lines.extend([
        f"\\put({fmt(left + width / 2.0)},{fmt(3.0)}){{\\makebox(0,0){{Productivity (share enacted)}}}}",
        f"\\put({fmt(5.0)},{fmt(bottom + height / 2.0)}){{\\rotatebox{{90}}{{Low-support passage}}}}",
        "\\end{picture}",
        "\\endgroup",
        "",
    ])
    (FIGURE_DIR / "productivity_low_support.tex").write_text("\n".join(lines))


def write_default_pass_deltas(averages: dict[str, dict[str, float]]) -> None:
    scenarios = [
        ("default-pass-mediation", "Mediation"),
        ("default-pass-challenge", "Challenge"),
        ("default-pass-adaptive-track", "Adaptive"),
        ("default-pass-sunset-trial", "Sunset"),
        ("default-pass-cross-bloc", "Cross-bloc"),
        ("default-pass-informed-guarded", "Guarded"),
    ]
    metrics = [
        ("productivity", "Prod.", "black"),
        ("policyShift", "Shift", "black!55"),
        ("proposerGain", "Prop.", "black!25"),
    ]
    baseline = averages["default-pass"]
    left_label, zero_x, scale = 34.0, 101.0, 82.0
    top, row_gap, bar_gap = 70.0, 10.0, 2.4
    lines = [
        "% Auto-generated by paper/scripts/generate_figures.py",
        "\\begingroup",
        "\\setlength{\\unitlength}{1mm}",
        "\\begin{picture}(128,82)",
        "\\scriptsize",
    ]
    for tick in (-0.6, -0.3, 0.0, 0.1):
        x = zero_x + tick * scale
        lines.extend([
            f"\\put({fmt(x)},{fmt(8.0)}){{\\color{{black!15}}\\line(0,1){{66.0}}}}",
            f"\\put({fmt(x)},{fmt(4.5)}){{\\makebox(0,0){{{tick:.1f}}}}}",
        ])
    lines.append(f"\\put({fmt(zero_x)},{fmt(8.0)}){{\\line(0,1){{66.0}}}}")
    for row_index, (key, label) in enumerate(scenarios):
        y = top - row_index * row_gap
        lines.append(f"\\put({fmt(left_label)},{fmt(y - 1.0)}){{\\makebox(0,0)[r]{{{label}}}}}")
        for metric_index, (field, _short, color) in enumerate(metrics):
            delta = averages[key][field] - baseline[field]
            bar_y = y + (1 - metric_index) * bar_gap
            if delta < 0:
                x = zero_x + delta * scale
                w = abs(delta) * scale
            else:
                x = zero_x
                w = delta * scale
            lines.append(f"\\put({fmt(x)},{fmt(bar_y)}){{\\color{{{color}}}\\rule{{{max(w, 0.3):.1f}mm}}{{1.8mm}}}}")
    legend_y = 78.0
    legend_x = 42.0
    for index, (_field, short, color) in enumerate(metrics):
        x = legend_x + index * 24.0
        lines.extend([
            f"\\put({fmt(x)},{fmt(legend_y)}){{\\color{{{color}}}\\rule{{5.0mm}}{{1.8mm}}}}",
            f"\\put({fmt(x + 7.0)},{fmt(legend_y + 0.2)}){{\\makebox(0,0)[l]{{{short} delta}}}}",
        ])
    lines.extend([
        f"\\put({fmt(69.0)},{fmt(0.5)}){{\\makebox(0,0){{Delta relative to open default-pass}}}}",
        "\\end{picture}",
        "\\endgroup",
        "",
    ])
    (FIGURE_DIR / "default_pass_deltas.tex").write_text("\n".join(lines))


def main() -> None:
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    averages = read_averages()
    write_productivity_low_support(averages)
    write_default_pass_deltas(averages)


if __name__ == "__main__":
    main()
