#!/usr/bin/env python3
"""Write compact LaTeX diagnostics tables for the paper."""

from __future__ import annotations

import csv
from pathlib import Path


ABLATION = Path("reports/ablation-analysis-summary.csv")
STRESS = Path("reports/manipulation-stress-summary.csv")
BRIDGE = Path("reports/empirical-bridge.csv")
OUT_MECHANISM = Path("paper/figures/mechanism_diagnostics_table.tex")
OUT_BRIDGE = Path("paper/figures/empirical_bridge_table.tex")

ABLATION_KEEP = {
    ("Policy tournament", "remove alternative comparison"),
    ("Risk routing", "replace citizen review with supermajority lane"),
    ("Anti-capture", "keep public-interest screen only"),
    ("Package bargaining", "replace multidimensional package with scalar package"),
    ("Reversibility", "remove active-law registry"),
}
STRESS_KEEP = {
    "Policy tournament clone/decoy attack",
    "Citizen-panel manipulation",
    "Bad-faith harm claims",
    "Astroturf objection pressure",
    "Agenda flooding",
}


def read(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise SystemExit(f"{path} is missing. Run make mechanism-diagnostics first.")
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle))


def tex(value: str) -> str:
    return (
        value.replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("_", "\\_")
    )


def signed(value: str) -> str:
    numeric = float(value)
    return f"{numeric:+.3f}"


SHORT_LABELS = {
    "remove alternative comparison": "No alternatives",
    "replace citizen review with supermajority lane": "No jury lane",
    "keep public-interest screen only": "Screen only",
    "replace multidimensional package with scalar package": "Scalar package",
    "remove active-law registry": "No registry",
    "Policy tournament clone/decoy attack": "Tournament attack",
    "Astroturf objection pressure": "Objection astroturf",
    "strategic clone and decoy variant": "Clones/decoys",
    "smaller, noisier, more manipulable panel": "Noisy panel",
    "lower harm threshold creates more false-positive review pressure": "Loose claims",
    "lower objection threshold and higher noise": "Astroturf/noise",
    "same agenda lottery under proposal flooding": "Proposal flood",
}


def short(value: str) -> str:
    return SHORT_LABELS.get(value, value)


def compact_value(value: str) -> str:
    if not value:
        return "---"
    try:
        return f"{float(value):.3f}"
    except ValueError:
        return value


DOES_NOT_VALIDATE = {
    "Bill attrition": "public benefit or law quality",
    "Floor consideration": "agenda fairness or policy merit",
    "Committee reporting from bill actions": "committee expertise or capture",
    "Roll-call coalition size": "public opinion",
    "Party unity": "public support or legitimacy",
    "Sponsor proposal concentration": "capture or representational equity",
}


def write_mechanism_table() -> None:
    ablations = [
        row for row in read(ABLATION)
        if (row["family"], row["ablation"]) in ABLATION_KEEP
    ]
    stresses = [
        row for row in read(STRESS)
        if row["test"] in STRESS_KEEP
    ]
    lines = [
        "% Auto-generated by scripts/reporting/write_paper_diagnostics.py",
        "\\begin{table*}",
        "  \\caption{Ablation diagnostics for selected mechanisms.}",
        "  \\label{tab:mechanism-ablation-diagnostics}",
        "  \\scriptsize",
        "  \\setlength{\\tabcolsep}{2.2pt}",
        "  \\resizebox{\\linewidth}{!}{%",
        "  \\begin{tabular}{llrrrr}",
        "    \\toprule",
        "    Mechanism & Removed or replaced component & Directional & Rev. mod. & Low supp. reduction & Admin added \\\\",
        "    \\midrule",
    ]
    for row in ablations:
        lines.append(
            "    "
            + " & ".join([
                tex(row["family"]),
                tex(short(row["ablation"])),
                signed(row["deltaDirectional"]),
                signed(row["deltaCompromise"]),
                signed(row["weakMandateReduction"]),
                signed(row["adminCostAdded"]),
            ])
            + " \\\\"
        )
    lines.extend([
        "    \\bottomrule",
        "  \\end{tabular}",
        "  }",
        "  \\par\\smallskip\\scriptsize \\emph{Note:} Positive values indicate how much the original mechanism improved relative to the ablated variant, except Admin added, where positive means additional procedural cost in the original mechanism.",
        "\\end{table*}",
        "",
        "\\begin{table*}",
        "  \\caption{Manipulation-stress losses for selected mechanisms.}",
        "  \\label{tab:manipulation-stress-diagnostics}",
        "  \\scriptsize",
        "  \\setlength{\\tabcolsep}{2.2pt}",
        "  \\resizebox{\\linewidth}{!}{%",
        "  \\begin{tabular}{llrrrr}",
        "    \\toprule",
        "    Stress case & Attack or perturbation & Directional loss & Rev. mod. loss & Low supp. added & Admin added \\\\",
        "    \\midrule",
    ])
    for row in stresses:
        lines.append(
            "    "
            + " & ".join([
                tex(short(row["test"])),
                tex(short(row["stressor"])),
                signed(row["directionalLoss"]),
                signed(row["compromiseLoss"]),
                signed(row["weakMandateAdded"]),
                signed(row["adminCostAdded"]),
            ])
            + " \\\\"
        )
    lines.extend([
        "    \\bottomrule",
        "  \\end{tabular}",
        "  }",
        "  \\par\\smallskip\\scriptsize \\emph{Note:} Positive values are losses or added burden under bounded manipulation stress. Low supp. is low-public-support enactment.",
        "\\end{table*}",
    ])
    OUT_MECHANISM.write_text("\n".join(lines) + "\n")


def write_bridge_table() -> None:
    rows = read(BRIDGE)
    lines = [
        "% Auto-generated by scripts/reporting/write_paper_diagnostics.py",
        "\\begin{table}",
        "  \\caption{Empirical flow smoke tests for the conventional benchmark. Raw inputs are optional and do not validate the synthetic welfare, revision moderation, harm, capture, or public-support metrics.}",
        "  \\label{tab:empirical-bridge}",
        "  \\Description{A generated table mapping empirical comparison signals to optional raw inputs and simulator proxies.}",
        "  \\scriptsize",
        "  \\setlength{\\tabcolsep}{2.6pt}",
        "  \\resizebox{\\linewidth}{!}{%",
        "  \\begin{tabular}{llll}",
        "    \\toprule",
        "    Signal & Raw & Simulator proxy & Does not validate \\\\",
        "    \\midrule",
    ]
    for row in rows[:6]:
        proxy = f"{row['simulatorScenario']}/{row['simulatorMetric']}" if row["simulatorScenario"] else "---"
        raw_value = compact_value(row["rawValue"])
        raw = f"{row['rawMetric']}={raw_value}"
        limitation = DOES_NOT_VALIDATE.get(row["signal"], "core normative metrics")
        lines.append(
            f"    {tex(row['signal'])} & {tex(raw)} & {tex(proxy)} & {tex(limitation)} \\\\"
        )
    lines.extend([
        "    \\bottomrule",
        "  \\end{tabular}",
        "  }",
        "\\end{table}",
    ])
    OUT_BRIDGE.write_text("\n".join(lines) + "\n")


def main() -> int:
    OUT_MECHANISM.parent.mkdir(parents=True, exist_ok=True)
    write_mechanism_table()
    write_bridge_table()
    print(f"Wrote {OUT_MECHANISM}")
    print(f"Wrote {OUT_BRIDGE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
