#!/usr/bin/env python3
"""Write compact LaTeX diagnostics tables for the paper."""

from __future__ import annotations

import csv
from pathlib import Path


ABLATION = Path("reports/ablation-analysis-summary.csv")
STRESS = Path("reports/manipulation-stress-summary.csv")
BRIDGE = Path("reports/empirical-bridge.csv")
OUT_MECHANISM = Path("paper/figures/mechanism_diagnostics_table.tex")
OUT_BRIDGE = Path("paper/figures/empirical_bridge_table.tex")

ABLATION_KEEP = {
    ("Policy tournament", "remove alternative comparison"),
    ("Risk routing", "replace citizen review with supermajority lane"),
    ("Anti-capture", "keep public-interest screen only"),
    ("Package bargaining", "replace multidimensional package with scalar package"),
    ("Reversibility", "remove active-law registry"),
}
STRESS_KEEP = {
    "Policy tournament clone/decoy attack",
    "Citizen-panel manipulation",
    "Bad-faith harm claims",
    "Astroturf objection pressure",
    "Agenda flooding",
}


def read(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise SystemExit(f"{path} is missing. Run make mechanism-diagnostics first.")
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle))


def tex(value: str) -> str:
    return (
        value.replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("_", "\\_")
    )


def signed(value: str) -> str:
    numeric = float(value)
    return f"{numeric:+.3f}"


SHORT_LABELS = {
    "remove alternative comparison": "No alternatives",
    "replace citizen review with supermajority lane": "No jury lane",
    "keep public-interest screen only": "Screen only",
    "replace multidimensional package with scalar package": "Scalar package",
    "remove active-law registry": "No registry",
    "Policy tournament clone/decoy attack": "Tournament attack",
    "Astroturf objection pressure": "Objection astroturf",
    "strategic clone and decoy variant": "Clones/decoys",
    "smaller, noisier, more manipulable panel": "Noisy panel",
    "lower harm threshold creates more false-positive review pressure": "Loose claims",
    "lower objection threshold and higher noise": "Astroturf/noise",
    "same agenda lottery under proposal flooding": "Proposal flood",
}


def short(value: str) -> str:
    return SHORT_LABELS.get(value, value)


def write_mechanism_table() -> None:
    ablations = [
        row for row in read(ABLATION)
        if (row["family"], row["ablation"]) in ABLATION_KEEP
    ]
    stresses = [
        row for row in read(STRESS)
        if row["test"] in STRESS_KEEP
    ]
    lines = [
        "% Auto-generated by scripts/reporting/write_paper_diagnostics.py",
        "\\begin{table*}",
        "  \\caption{Diagnostic follow-ups for selected mechanisms. Ablation rows compare a full mechanism with a nearby removal; stress rows compare a reference with a manipulation-prone variant or stress case. Positive directional changes favor the full mechanism for ablations, while positive losses indicate vulnerability for stress tests.}",
        "  \\label{tab:mechanism-diagnostics}",
        "  \\Description{A generated diagnostics table summarizing mechanism ablations and manipulation stress tests.}",
        "  \\scriptsize",
        "  \\begin{tabular}{lllrrrr}",
        "    \\toprule",
        "    Type & Mechanism & Comparison & Dir. & Comp. & Weak mand. & Admin \\\\",
        "    \\midrule",
    ]
    for row in ablations:
        lines.append(
            "    "
            + " & ".join([
                "Ablation",
                tex(row["family"]),
                tex(short(row["ablation"])),
                signed(row["deltaDirectional"]),
                signed(row["deltaCompromise"]),
                signed(row["weakMandateReduction"]),
                signed(row["adminCostAdded"]),
            ])
            + " \\\\"
        )
    for row in stresses:
        lines.append(
            "    "
            + " & ".join([
                "Stress",
                tex(short(row["test"])),
                tex(short(row["stressor"])),
                signed(row["directionalLoss"]),
                signed(row["compromiseLoss"]),
                signed(row["weakMandateAdded"]),
                signed(row["adminCostAdded"]),
            ])
            + " \\\\"
        )
    lines.extend([
        "    \\bottomrule",
        "  \\end{tabular}",
        "  \\par\\smallskip\\footnotesize \\emph{Note:} For ablations, weak mandate is a reduction, so positive is better; admin is added cost, so positive is worse. For stress rows, all positive entries are losses or added burden.",
        "\\end{table*}",
    ])
    OUT_MECHANISM.write_text("\n".join(lines) + "\n")


def write_bridge_table() -> None:
    rows = read(BRIDGE)
    lines = [
        "% Auto-generated by scripts/reporting/write_paper_diagnostics.py",
        "\\begin{table}",
        "  \\caption{Empirical validation bridge. Raw inputs are optional; the table records whether each real-world signal has a local raw summary and the current simulator proxy used for calibration screening.}",
        "  \\label{tab:empirical-bridge}",
        "  \\Description{A generated table mapping desired empirical validation signals to optional raw inputs and simulator proxies.}",
        "  \\scriptsize",
        "  \\begin{tabular}{lll}",
        "    \\toprule",
        "    Signal & Simulator proxy & Status \\\\",
        "    \\midrule",
    ]
    for row in rows[:6]:
        proxy = f"{row['simulatorScenario']}/{row['simulatorMetric']}" if row["simulatorScenario"] else "---"
        lines.append(
            f"    {tex(row['signal'])} & {tex(proxy)} & {tex(row['bridgeStatus'])} \\\\"
        )
    lines.extend([
        "    \\bottomrule",
        "  \\end{tabular}",
        "\\end{table}",
    ])
    OUT_BRIDGE.write_text("\n".join(lines) + "\n")


def main() -> int:
    OUT_MECHANISM.parent.mkdir(parents=True, exist_ok=True)
    write_mechanism_table()
    write_bridge_table()
    print(f"Wrote {OUT_MECHANISM}")
    print(f"Wrote {OUT_BRIDGE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
