package congresssim.institution.chamber;

public enum BicameralConflictMode {
    SECOND_CHAMBER_KILL,
    REVISION_COUNCIL,
    SECOND_CHAMBER_AMENDMENT,
    SUSPENSIVE_VETO,
    LIMITED_NAVETTE,
    JOINT_SITTING,
    MEDIATION_COMMITTEE,
    LAST_OFFER_BARGAINING,
    LOWER_OVERRIDE_AFTER_DISAGREEMENT
}
