package congresssim.simulation;

public enum CommitteeComposition {
    REPRESENTATIVE,
    MAJORITY_CONTROLLED,
    POLARIZED,
    EXPERT,
    CAPTURED,
    PROPORTIONAL_PARTY,
    FORCED_PARTY_BALANCE,
    MINORITY_PROTECTED,
    RANDOM_LOTTERY,
    ROTATING_LOTTERY,
    INDEPENDENT_EXPERT,
    LEADERSHIP_STACKED,
    ISSUE_EXPERT,
    EXPERTISE_QUALIFIED_LOTTERY,
    MIXED_LEGISLATOR_CITIZEN,
    MINORITY_VETO_HIGH_RISK,
    MIXED_PARLIAMENTARIAN_CITIZEN,
    OPPOSITION_CHAIRED,
    PUBLIC_ACCOUNTS_STYLE
}
