package congresssim.simulation;

public enum SeatAllocationProfile {
    EQUAL_POPULATION_SINGLE_MEMBER,
    PROPORTIONAL_PARTY_LIST,
    MIXED_MEMBER,
    EQUAL_TERRITORIAL,
    BANDED_TERRITORIAL,
    MALAPPORTIONED_TERRITORIAL,
    APPOINTED,
    MIXED_ELECTED_APPOINTED
}
